### ISSUE TITLE
Invalid kata name errors

### ISSUE THREAD

**Issue by soudy** [microsoft/QuantumKatas#106] opened 2019-05-01 19:39 UTC
I installed IQ# as described [here](https://docs.microsoft.com/en-us/quantum/install-guide/jupyter?view=qsharp-preview), cloned this repository and tried to run the BasicGates Jupyter notebook. However, when trying to run any task I get the following error:
```
Invalid kata name: T11_StateFlip_Test
```
Some information:
- Ubuntu 16.04
- Python 3.7.1
- Jupyter Notebook 4.4.0
 ```bash
$ dotnet iqsharp --version
Language kernel: 0.5.1904.1302
Jupyter core: 1.1.13141.0
```

Removing the `%kata` lines at the top of each block fixes this issue.

**Comment by tcNickolas** [comment] 2019-05-01 22:08
Odd, this looks like the notebook doesn't recognize the test which covers the task (that's what `%kata` defines). Could you try to execute `%workspace reload` (in a separate cell after the `%package Microsoft.Quantum.Katas` cell) and show us the results? This should give us some info about what went wrong.

**Comment by soudy** [comment] 2019-05-01 23:04
@tcNickolas Hmm, that just gives an empty output:
![2019-05-02-010353_1045x485_scrot](https://user-images.githubusercontent.com/7383594/57048903-4456f100-6c76-11e9-9222-3329e4273954.png)

**Comment by tcNickolas** [comment] 2019-05-01 23:32
Could you try to build the kata as a project from command line (go to BasicGates folder and do `dotnet build`)? If there are any errors building it, it would explain this behavior.

**Comment by soudy** [comment] 2019-05-02 09:37
No errors:
```
$ dotnet build
Microsoft (R) Build Engine version 16.0.450+ga8dc7f1d34 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 7.27 sec for /home/soud/Tech/Quantum Computing/QuantumKatas/BasicGates/BasicGates.csproj.
  Restore completed in 7.67 sec for /home/soud/Tech/Quantum Computing/QuantumKatas/BasicGates/BasicGates.csproj.
  
  ____________________________________________
  
  Q#: Success! (0 errors, 0 warnings) 
  BasicGates -> /home/soud/Tech/Quantum Computing/QuantumKatas/BasicGates/bin/Debug/netcoreapp2.1/BasicGates.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:15.95
```

**Comment by tcNickolas** [comment] 2019-05-02 18:23
Curiouser and curiouser.... We'll try to reproduce this on our side, but this will take us some time, sorry! 

To get you unblocked in the meantime, do you want to try the online version of the Notebooks [on Binder](https://mybinder.org/v2/gh/Microsoft/QuantumKatas/master?filepath=index.ipynb)? The first four katas are available there, and I've checked that they work on Ubuntu.

**Comment by anpaz-msft** [comment] 2019-05-02 20:34
As another option to unblock, there is a Dockerfile in the root folder, that should let you build a docker image with everything you need to run. Instructions on how to use it are in the README.md

**Comment by anpaz-msft** [comment] 2019-05-03 23:18
I tried today to reproduce the problem, but no luck.
Created an Ubuntu 16.04 image:
```
# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
```
Installed 
- .NET core 2.2.203
- Jupyter 4.4
- IQ# 0.5.1904.1302

And the `BasicGates` kata notebook is working as expected. I had to manually add `~/.dotnet/tools` to the path, but other than that I did nothing special. 

My recommendation again is going to be building a docker image from the Dockerfile. If you really want to figure out why it is not working, we can explain how to turn on debug logs and we'll take it from there.

**Comment by soudy** [comment] 2019-05-04 14:23
@anpaz-msft thanks for checking. Docker image works, must be something on my system.

**Comment by tcNickolas** [comment] 2019-05-21 04:34
I finally got to installing IQ# on Ubuntu (though I have 18.04), and couldn't reproduce this issue either - didn't even have to modify any paths manually.

I'll close this issue, since we don't really have a path to further investigation. Sorry we couldn't figure it out, and I hope using Docker image works for you!

**Closed by tcNickolas** 2019-05-21 04:34 UTC

**Comment by geduardo** [comment] 2019-08-15 02:09
@tcNickolas 
I had the exact same issue (but on windows) and running %workspace reload in a separate cell solved the issue.
I don't know if this issue is general or very specific. Maybe it is worth to comment in the intro of each kata.

**Comment by tcNickolas** [comment] 2019-08-15 07:30
This is weird... The katas that need `%workspace reload` (the ones that use custom simulator) have this cell right after the `%package` one, and the katas that don't have it shouldn't need it to run.
